name: dev-environment
services:
  blazor:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: blazor-frontend
    volumes:
      - ./:/app
      - ./newFrontend/keys:/app/newFrontend/keys
    working_dir: /app/newFrontend/newFrontend
    ports:
      - 5001:8080
    command: dotnet watch run
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
     - development
    depends_on:
      api:
        condition: service_started
        restart: true
 
  api:
    image: mcr.microsoft.com/dotnet/sdk:10.0 
    container_name: api-backend
    volumes:
      - ./:/app
    working_dir: /app/Backend
    ports:
      - 8000:8080
    command: dotnet run
    networks:
      - development
    environment:
      - TZ=America/Sao_Paulo
      - DOTNET_RUNNING_IN_CONTAINER=true
    depends_on:
      db:
        condition: service_started
        restart: true

  db:
    image: mcr.microsoft.com/azure-sql-edge
    user: root
    cap_add:
      - SYS_PTRACE
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=TivitDioBootcamp*
    hostname: "db"
    ports:
      - "1433:1433"
    volumes:
      - mssql-volume:/var/opt/mssql
    networks:
      - development

networks:
  development:

volumes:
  mssql-volume:
